### ISSUE TITLE
Do we have any estimation when Add Resource will be ready?

### ISSUE THREAD

**Issue by ekeren** [gonzoua/xcs2#1]

**Comment by ikrabbe** [comment]
As "add resource" is a quite complex operation, I built a little tool that currently just add a resource to a project, with a few command line options.
This tool is far from usable globally, as it is not configurable to work out of the [XCodeControl](https://github.com/ikrabbe/XCodeControl) build directory yet, but could be modified in a very simple way to work globally and can be extended easily to do more complex or just other operations than adding a source file. I will add some hints and documentation how to go further soon.

But all I wanted right now with it is to add a source file to a project and add that source file as a build rule to all targets.

Please contact me if you want to get more from this tool: [XCodeControl](https://github.com/ikrabbe/XCodeControl)
